spring:

  config:
    import: properties/auth.yml

  sql:
    init:
      mode: always


  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:3306/squadmap
    username: ron2
    password: aaron


  jpa:
    hibernate:
      ddl-auto: create

    defer-datasource-initialization: true

    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

    open-in-view: false
