spring:

  config:
    import:
    - properties/auth.yml
    - properties/datasource.yml

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create

    defer-datasource-initialization: true

    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

    open-in-view: false

  redis:
    port: 6379
    host: localhost

  cache:
    type: redis
    redis:
      time-to-live: 5000000
